language: node_js
node_js:
  - 12
services:
  - docker

script:
  - docker --version
  - docker-compose build -f docker-compose-build.yaml

deploy:
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker-compose -f docker-compose-build.yaml push
