language: node_js
node_js:
  - 12
services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push
